// <auto-generated />
using System;
using GPS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPS.Api.Migrations
{
    [DbContext(typeof(GpsContext))]
    partial class GpsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("GPS.Api.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "user1",
                            Dob = new DateOnly(1990, 1, 1),
                            Email = "user1@example.com",
                            OwnerID = "owner1",
                            UserPassword = "password1"
                        },
                        new
                        {
                            UserID = "user2",
                            Dob = new DateOnly(1992, 2, 2),
                            Email = "user2@example.com",
                            OwnerID = "owner2",
                            UserPassword = "password2"
                        });
                });

            modelBuilder.Entity("GPS.Api.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleNum");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleNum = 1,
                            Latitude = 0.0001,
                            Longitude = 1.0000000000000001E-05,
                            Make = "make1",
                            Model = "model1",
                            OwnerId = "ownerId1",
                            Year = 2021
                        },
                        new
                        {
                            VehicleNum = 2,
                            Latitude = 0.00020000000000000001,
                            Longitude = 2.0000000000000002E-05,
                            Make = "make2",
                            Model = "model2",
                            OwnerId = "ownerId2",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
